pluginGroup = com.github.mateuszpodeszwa.consolemvc
pluginName = ConsoleMVC CvwSupport
pluginVersion = 0.1.0

platformVersion = 2025.1
pluginSinceBuild = 251

platformPlugins =
platformBundledPlugins =

gradleVersion = 9.4.1

kotlin.stdlib.default.dependency = false

org.gradle.configuration-cache = true
org.gradle.caching = true
