<Project>
  <Import Project="Plugin.props" />
  <PropertyGroup>
    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
    <OutputPath>bin\$(MSBuildProjectName)\$(Configuration)\</OutputPath>
    <RootNamespace>CvwSupport</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
