using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace CvwSupport;

/// <summary>
/// Generates a synthetic C# document from a .cvw file, mirroring the exact
/// transformation performed by the ConsoleMVC source generator.
///
/// The generated document wraps the .cvw code body in:
///   using ConsoleMVC.Mvc;
///   using {each @using};
///   namespace {RootNamespace}.Views.{Controller} {
///     public class {FileName} : ConsoleView&lt;{@model type}&gt; {
///       public override NavigationResult Render({@model type} Model) {
///         {code body}
///       }
///     }
///   }
///
/// A range map is produced that maps character offsets between the original .cvw
/// and the generated C# document, enabling accurate error placement, completion,
/// and navigation.
/// </summary>
public class CvwGeneratedDocumentFactory
{
    /// <summary>
    /// Result of generating a virtual C# document from a .cvw file.
    /// </summary>
    public class GenerationResult
    {
        /// <summary>The full generated C# source text.</summary>
        public string GeneratedText { get; init; } = "";

        /// <summary>
        /// Offset in the generated text where the code body begins.
        /// This corresponds to the first character of the code body
        /// inside the Render() method.
        /// </summary>
        public int GeneratedCodeBodyOffset { get; init; }

        /// <summary>
        /// Offset in the original .cvw text where the code body begins.
        /// </summary>
        public int OriginalCodeBodyOffset { get; init; }

        /// <summary>The parsed file data.</summary>
        public CvwFileParser Parser { get; init; } = new();

        /// <summary>
        /// Offsets in the generated text where the @model type appears.
        /// The model type appears in two places: ConsoleView&lt;T&gt; and the Render parameter.
        /// </summary>
        public List<int> GeneratedModelTypeOffsets { get; init; } = new();

        /// <summary>
        /// Offsets in the generated text where each @using namespace appears
        /// (in the "using X;" directives). Parallel to Parser.UsingLocations.
        /// </summary>
        public List<int> GeneratedUsingOffsets { get; init; } = new();
    }

    /// <summary>
    /// Generates a virtual C# document from a .cvw file.
    /// </summary>
    /// <param name="cvwContent">The raw text content of the .cvw file.</param>
    /// <param name="filePath">The file path, used to extract controller and action names.</param>
    /// <param name="rootNamespace">The project's root namespace (defaults to "ConsoleMVC").</param>
    /// <returns>The generation result, or null if the file has no @model directive.</returns>
    public GenerationResult? Generate(string cvwContent, string filePath, string rootNamespace = "ConsoleMVC")
    {
        var parser = new CvwFileParser();
        parser.Parse(cvwContent);

        if (parser.ModelType == null)
            return null;

        // Extract controller name and file name from path
        var normalizedPath = filePath.Replace('\\', '/');
        var pathParts = normalizedPath.Split('/');

        string? controllerName = null;
        for (var i = 0; i < pathParts.Length - 1; i++)
        {
            if (string.Equals(pathParts[i], "Views", StringComparison.OrdinalIgnoreCase)
                && i + 1 < pathParts.Length - 1)
            {
                controllerName = pathParts[i + 1];
                break;
            }
        }

        controllerName ??= "Unknown";
        var fileName = Path.GetFileNameWithoutExtension(filePath);

        // Build the generated document
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine($"// Virtual document for {controllerName}/{fileName}.cvw");
        sb.AppendLine("// </auto-generated>");

        // Using directives
        sb.AppendLine("using ConsoleMVC.Mvc;");
        var generatedUsingOffsets = new List<int>();
        foreach (var u in parser.Usings)
        {
            var usingOffset = sb.Length + "using ".Length;
            generatedUsingOffsets.Add(usingOffset);
            sb.AppendLine($"using {u};");
        }
        sb.AppendLine();

        // Namespace and class
        var generatedModelTypeOffsets = new List<int>();
        sb.AppendLine($"namespace {rootNamespace}.Views.{controllerName}");
        sb.AppendLine("{");

        // Track @model type in "ConsoleView<ModelType>"
        var classLinePrefix = $"    public class {fileName} : ConsoleView<";
        var modelOffset1 = sb.Length + classLinePrefix.Length;
        generatedModelTypeOffsets.Add(modelOffset1);
        sb.AppendLine($"{classLinePrefix}{parser.ModelType}>");

        sb.AppendLine("    {");

        // Track @model type in "Render(ModelType Model)"
        var renderPrefix = "        public override NavigationResult Render(";
        var modelOffset2 = sb.Length + renderPrefix.Length;
        generatedModelTypeOffsets.Add(modelOffset2);
        sb.AppendLine($"{renderPrefix}{parser.ModelType} Model)");

        sb.AppendLine("        {");

        // Record where the code body starts in the generated document
        var generatedCodeBodyOffset = sb.Length;

        // Indent each code body line with 12 spaces (3 levels of 4-space indent)
        var codeLines = parser.CodeBody.Split('\n');
        foreach (var line in codeLines)
        {
            sb.Append("            ");
            sb.AppendLine(line);
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new GenerationResult
        {
            GeneratedText = sb.ToString(),
            GeneratedCodeBodyOffset = generatedCodeBodyOffset,
            OriginalCodeBodyOffset = parser.CodeBodyOffset,
            Parser = parser,
            GeneratedModelTypeOffsets = generatedModelTypeOffsets,
            GeneratedUsingOffsets = generatedUsingOffsets
        };
    }

    /// <summary>
    /// Maps an offset in the original .cvw code body to the corresponding offset
    /// in the generated C# document.
    /// </summary>
    public static int MapOriginalToGenerated(GenerationResult result, int originalOffset)
    {
        if (originalOffset < result.OriginalCodeBodyOffset)
            return -1; // In the directive section, no direct mapping

        var relativeOffset = originalOffset - result.OriginalCodeBodyOffset;

        // Account for the 12-space indentation added to each line
        var codeBody = result.Parser.CodeBody;
        var lineCount = 0;
        for (var i = 0; i < relativeOffset && i < codeBody.Length; i++)
        {
            if (codeBody[i] == '\n') lineCount++;
        }

        // Each line in the generated doc has 12 extra chars of indentation
        // plus we need to account for \r\n vs \n differences in AppendLine
        return result.GeneratedCodeBodyOffset + relativeOffset + (lineCount * 12);
    }

    /// <summary>
    /// Maps an offset in the generated C# document back to the original .cvw file.
    /// </summary>
    public static int MapGeneratedToOriginal(GenerationResult result, int generatedOffset)
    {
        if (generatedOffset < result.GeneratedCodeBodyOffset)
            return -1; // In the generated header, no mapping back

        var relativeOffset = generatedOffset - result.GeneratedCodeBodyOffset;

        // Reverse the indentation mapping
        var generatedCode = result.GeneratedText.Substring(result.GeneratedCodeBodyOffset);
        var actualOffset = 0;
        var lineStart = true;
        var indentCharsSkipped = 0;

        for (var i = 0; i < relativeOffset && i < generatedCode.Length; i++)
        {
            if (lineStart && generatedCode[i] == ' ' && indentCharsSkipped < 12)
            {
                indentCharsSkipped++;
                if (indentCharsSkipped == 12) lineStart = false;
                continue; // Skip indentation chars
            }

            if (generatedCode[i] == '\n')
            {
                lineStart = true;
                indentCharsSkipped = 0;
            }
            else
            {
                lineStart = false;
            }

            actualOffset++;
        }

        return result.OriginalCodeBodyOffset + actualOffset;
    }
}
